// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fedn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.fednclient.grpc;

@kotlin.jvm.JvmName("-initializeclient")
public inline fun client(block: com.example.fednclient.grpc.ClientKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.Client =
  com.example.fednclient.grpc.ClientKt.Dsl._create(com.example.fednclient.grpc.Client.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.Client`
 */
public object ClientKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.fednclient.grpc.Client.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.fednclient.grpc.Client.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.fednclient.grpc.Client = _builder.build()

    /**
     * `.grpc.Role role = 1;`
     */
    public var role: com.example.fednclient.grpc.Role
      @JvmName("getRole")
      get() = _builder.getRole()
      @JvmName("setRole")
      set(value) {
        _builder.setRole(value)
      }
    public var roleValue: kotlin.Int
      @JvmName("getRoleValue")
      get() = _builder.getRoleValue()
      @JvmName("setRoleValue")
      set(value) {
        _builder.setRoleValue(value)
      }
    /**
     * `.grpc.Role role = 1;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.fednclient.grpc.Client.copy(block: com.example.fednclient.grpc.ClientKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.Client =
  com.example.fednclient.grpc.ClientKt.Dsl._create(this.toBuilder()).apply { block() }._build()

