// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fedn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.fednclient.grpc;

@kotlin.jvm.JvmName("-initializeclientAvailableMessage")
public inline fun clientAvailableMessage(block: com.example.fednclient.grpc.ClientAvailableMessageKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.ClientAvailableMessage =
  com.example.fednclient.grpc.ClientAvailableMessageKt.Dsl._create(com.example.fednclient.grpc.ClientAvailableMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.ClientAvailableMessage`
 */
public object ClientAvailableMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.fednclient.grpc.ClientAvailableMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.fednclient.grpc.ClientAvailableMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.fednclient.grpc.ClientAvailableMessage = _builder.build()

    /**
     * `.grpc.Client sender = 1;`
     */
    public var sender: com.example.fednclient.grpc.Client
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * `.grpc.Client sender = 1;`
     */
    public fun clearSender() {
      _builder.clearSender()
    }
    /**
     * `.grpc.Client sender = 1;`
     * @return Whether the sender field is set.
     */
    public fun hasSender(): kotlin.Boolean {
      return _builder.hasSender()
    }

    /**
     * `string data = 2;`
     */
    public var data: kotlin.String
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * `string data = 2;`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `string timestamp = 3;`
     */
    public var timestamp: kotlin.String
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * `string timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.fednclient.grpc.ClientAvailableMessage.copy(block: com.example.fednclient.grpc.ClientAvailableMessageKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.ClientAvailableMessage =
  com.example.fednclient.grpc.ClientAvailableMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.fednclient.grpc.ClientAvailableMessageOrBuilder.senderOrNull: com.example.fednclient.grpc.Client?
  get() = if (hasSender()) getSender() else null

