// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fednclient.grpc;

/**
 * Protobuf type {@code grpc.ClientList}
 */
public final class ClientList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.ClientList)
    ClientListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientList.newBuilder() to construct.
  private ClientList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientList() {
    client_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.fednclient.grpc.Fedn.internal_static_grpc_ClientList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.fednclient.grpc.Fedn.internal_static_grpc_ClientList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.fednclient.grpc.ClientList.class, com.example.fednclient.grpc.ClientList.Builder.class);
  }

  public static final int CLIENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.fednclient.grpc.Client> client_;
  /**
   * <code>repeated .grpc.Client client = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.fednclient.grpc.Client> getClientList() {
    return client_;
  }
  /**
   * <code>repeated .grpc.Client client = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.fednclient.grpc.ClientOrBuilder> 
      getClientOrBuilderList() {
    return client_;
  }
  /**
   * <code>repeated .grpc.Client client = 1;</code>
   */
  @java.lang.Override
  public int getClientCount() {
    return client_.size();
  }
  /**
   * <code>repeated .grpc.Client client = 1;</code>
   */
  @java.lang.Override
  public com.example.fednclient.grpc.Client getClient(int index) {
    return client_.get(index);
  }
  /**
   * <code>repeated .grpc.Client client = 1;</code>
   */
  @java.lang.Override
  public com.example.fednclient.grpc.ClientOrBuilder getClientOrBuilder(
      int index) {
    return client_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < client_.size(); i++) {
      output.writeMessage(1, client_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < client_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, client_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.fednclient.grpc.ClientList)) {
      return super.equals(obj);
    }
    com.example.fednclient.grpc.ClientList other = (com.example.fednclient.grpc.ClientList) obj;

    if (!getClientList()
        .equals(other.getClientList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getClientCount() > 0) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClientList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.fednclient.grpc.ClientList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.fednclient.grpc.ClientList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.fednclient.grpc.ClientList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.fednclient.grpc.ClientList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.fednclient.grpc.ClientList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.ClientList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.ClientList)
      com.example.fednclient.grpc.ClientListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.fednclient.grpc.Fedn.internal_static_grpc_ClientList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.fednclient.grpc.Fedn.internal_static_grpc_ClientList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.fednclient.grpc.ClientList.class, com.example.fednclient.grpc.ClientList.Builder.class);
    }

    // Construct using com.example.fednclient.grpc.ClientList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (clientBuilder_ == null) {
        client_ = java.util.Collections.emptyList();
      } else {
        client_ = null;
        clientBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.fednclient.grpc.Fedn.internal_static_grpc_ClientList_descriptor;
    }

    @java.lang.Override
    public com.example.fednclient.grpc.ClientList getDefaultInstanceForType() {
      return com.example.fednclient.grpc.ClientList.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.fednclient.grpc.ClientList build() {
      com.example.fednclient.grpc.ClientList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.fednclient.grpc.ClientList buildPartial() {
      com.example.fednclient.grpc.ClientList result = new com.example.fednclient.grpc.ClientList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.fednclient.grpc.ClientList result) {
      if (clientBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          client_ = java.util.Collections.unmodifiableList(client_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
    }

    private void buildPartial0(com.example.fednclient.grpc.ClientList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.fednclient.grpc.ClientList) {
        return mergeFrom((com.example.fednclient.grpc.ClientList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.fednclient.grpc.ClientList other) {
      if (other == com.example.fednclient.grpc.ClientList.getDefaultInstance()) return this;
      if (clientBuilder_ == null) {
        if (!other.client_.isEmpty()) {
          if (client_.isEmpty()) {
            client_ = other.client_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureClientIsMutable();
            client_.addAll(other.client_);
          }
          onChanged();
        }
      } else {
        if (!other.client_.isEmpty()) {
          if (clientBuilder_.isEmpty()) {
            clientBuilder_.dispose();
            clientBuilder_ = null;
            client_ = other.client_;
            bitField0_ = (bitField0_ & ~0x00000001);
            clientBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getClientFieldBuilder() : null;
          } else {
            clientBuilder_.addAllMessages(other.client_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.fednclient.grpc.Client m =
                  input.readMessage(
                      com.example.fednclient.grpc.Client.parser(),
                      extensionRegistry);
              if (clientBuilder_ == null) {
                ensureClientIsMutable();
                client_.add(m);
              } else {
                clientBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.fednclient.grpc.Client> client_ =
      java.util.Collections.emptyList();
    private void ensureClientIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        client_ = new java.util.ArrayList<com.example.fednclient.grpc.Client>(client_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.fednclient.grpc.Client, com.example.fednclient.grpc.Client.Builder, com.example.fednclient.grpc.ClientOrBuilder> clientBuilder_;

    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public java.util.List<com.example.fednclient.grpc.Client> getClientList() {
      if (clientBuilder_ == null) {
        return java.util.Collections.unmodifiableList(client_);
      } else {
        return clientBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public int getClientCount() {
      if (clientBuilder_ == null) {
        return client_.size();
      } else {
        return clientBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public com.example.fednclient.grpc.Client getClient(int index) {
      if (clientBuilder_ == null) {
        return client_.get(index);
      } else {
        return clientBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder setClient(
        int index, com.example.fednclient.grpc.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientIsMutable();
        client_.set(index, value);
        onChanged();
      } else {
        clientBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder setClient(
        int index, com.example.fednclient.grpc.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.set(index, builderForValue.build());
        onChanged();
      } else {
        clientBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder addClient(com.example.fednclient.grpc.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientIsMutable();
        client_.add(value);
        onChanged();
      } else {
        clientBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder addClient(
        int index, com.example.fednclient.grpc.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientIsMutable();
        client_.add(index, value);
        onChanged();
      } else {
        clientBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder addClient(
        com.example.fednclient.grpc.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.add(builderForValue.build());
        onChanged();
      } else {
        clientBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder addClient(
        int index, com.example.fednclient.grpc.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.add(index, builderForValue.build());
        onChanged();
      } else {
        clientBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder addAllClient(
        java.lang.Iterable<? extends com.example.fednclient.grpc.Client> values) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, client_);
        onChanged();
      } else {
        clientBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        clientBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public Builder removeClient(int index) {
      if (clientBuilder_ == null) {
        ensureClientIsMutable();
        client_.remove(index);
        onChanged();
      } else {
        clientBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public com.example.fednclient.grpc.Client.Builder getClientBuilder(
        int index) {
      return getClientFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public com.example.fednclient.grpc.ClientOrBuilder getClientOrBuilder(
        int index) {
      if (clientBuilder_ == null) {
        return client_.get(index);  } else {
        return clientBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public java.util.List<? extends com.example.fednclient.grpc.ClientOrBuilder> 
         getClientOrBuilderList() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(client_);
      }
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public com.example.fednclient.grpc.Client.Builder addClientBuilder() {
      return getClientFieldBuilder().addBuilder(
          com.example.fednclient.grpc.Client.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public com.example.fednclient.grpc.Client.Builder addClientBuilder(
        int index) {
      return getClientFieldBuilder().addBuilder(
          index, com.example.fednclient.grpc.Client.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.Client client = 1;</code>
     */
    public java.util.List<com.example.fednclient.grpc.Client.Builder> 
         getClientBuilderList() {
      return getClientFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.fednclient.grpc.Client, com.example.fednclient.grpc.Client.Builder, com.example.fednclient.grpc.ClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.fednclient.grpc.Client, com.example.fednclient.grpc.Client.Builder, com.example.fednclient.grpc.ClientOrBuilder>(
                client_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.ClientList)
  }

  // @@protoc_insertion_point(class_scope:grpc.ClientList)
  private static final com.example.fednclient.grpc.ClientList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.fednclient.grpc.ClientList();
  }

  public static com.example.fednclient.grpc.ClientList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientList>
      PARSER = new com.google.protobuf.AbstractParser<ClientList>() {
    @java.lang.Override
    public ClientList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.fednclient.grpc.ClientList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

