// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fedn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.fednclient.grpc;

@kotlin.jvm.JvmName("-initializeconnectionRequest")
public inline fun connectionRequest(block: com.example.fednclient.grpc.ConnectionRequestKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.ConnectionRequest =
  com.example.fednclient.grpc.ConnectionRequestKt.Dsl._create(com.example.fednclient.grpc.ConnectionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.ConnectionRequest`
 */
public object ConnectionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.fednclient.grpc.ConnectionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.fednclient.grpc.ConnectionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.fednclient.grpc.ConnectionRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.fednclient.grpc.ConnectionRequest.copy(block: com.example.fednclient.grpc.ConnectionRequestKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.ConnectionRequest =
  com.example.fednclient.grpc.ConnectionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

