// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fednclient.grpc;

public interface ControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  java.util.List<com.example.fednclient.grpc.Parameter> 
      getParameterList();
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  com.example.fednclient.grpc.Parameter getParameter(int index);
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  int getParameterCount();
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  java.util.List<? extends com.example.fednclient.grpc.ParameterOrBuilder> 
      getParameterOrBuilderList();
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  com.example.fednclient.grpc.ParameterOrBuilder getParameterOrBuilder(
      int index);
}
