// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fednclient.grpc;

public interface ControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Command command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.grpc.Command command = 1;</code>
   * @return The command.
   */
  com.example.fednclient.grpc.Command getCommand();

  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  java.util.List<com.example.fednclient.grpc.Parameter> 
      getParameterList();
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  com.example.fednclient.grpc.Parameter getParameter(int index);
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  int getParameterCount();
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  java.util.List<? extends com.example.fednclient.grpc.ParameterOrBuilder> 
      getParameterOrBuilderList();
  /**
   * <code>repeated .grpc.Parameter parameter = 2;</code>
   */
  com.example.fednclient.grpc.ParameterOrBuilder getParameterOrBuilder(
      int index);
}
