// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fednclient.grpc;

/**
 * Protobuf service {@code grpc.Control}
 */
public  abstract class Control
    implements com.google.protobuf.Service {
  protected Control() {}

  public interface Interface {
    /**
     * <code>rpc Start(.grpc.ControlRequest) returns (.grpc.ControlResponse);</code>
     */
    public abstract void start(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done);

    /**
     * <code>rpc Stop(.grpc.ControlRequest) returns (.grpc.ControlResponse);</code>
     */
    public abstract void stop(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done);

    /**
     * <code>rpc Configure(.grpc.ControlRequest) returns (.grpc.ReportResponse);</code>
     */
    public abstract void configure(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done);

    /**
     * <code>rpc Report(.grpc.ControlRequest) returns (.grpc.ReportResponse);</code>
     */
    public abstract void report(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new Control() {
      @java.lang.Override
      public  void start(
          com.google.protobuf.RpcController controller,
          com.example.fednclient.grpc.ControlRequest request,
          com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done) {
        impl.start(controller, request, done);
      }

      @java.lang.Override
      public  void stop(
          com.google.protobuf.RpcController controller,
          com.example.fednclient.grpc.ControlRequest request,
          com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done) {
        impl.stop(controller, request, done);
      }

      @java.lang.Override
      public  void configure(
          com.google.protobuf.RpcController controller,
          com.example.fednclient.grpc.ControlRequest request,
          com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done) {
        impl.configure(controller, request, done);
      }

      @java.lang.Override
      public  void report(
          com.google.protobuf.RpcController controller,
          com.example.fednclient.grpc.ControlRequest request,
          com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done) {
        impl.report(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.start(controller, (com.example.fednclient.grpc.ControlRequest)request);
          case 1:
            return impl.stop(controller, (com.example.fednclient.grpc.ControlRequest)request);
          case 2:
            return impl.configure(controller, (com.example.fednclient.grpc.ControlRequest)request);
          case 3:
            return impl.report(controller, (com.example.fednclient.grpc.ControlRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
          case 1:
            return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
          case 2:
            return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
          case 3:
            return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.fednclient.grpc.ControlResponse.getDefaultInstance();
          case 1:
            return com.example.fednclient.grpc.ControlResponse.getDefaultInstance();
          case 2:
            return com.example.fednclient.grpc.ReportResponse.getDefaultInstance();
          case 3:
            return com.example.fednclient.grpc.ReportResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Start(.grpc.ControlRequest) returns (.grpc.ControlResponse);</code>
   */
  public abstract void start(
      com.google.protobuf.RpcController controller,
      com.example.fednclient.grpc.ControlRequest request,
      com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done);

  /**
   * <code>rpc Stop(.grpc.ControlRequest) returns (.grpc.ControlResponse);</code>
   */
  public abstract void stop(
      com.google.protobuf.RpcController controller,
      com.example.fednclient.grpc.ControlRequest request,
      com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done);

  /**
   * <code>rpc Configure(.grpc.ControlRequest) returns (.grpc.ReportResponse);</code>
   */
  public abstract void configure(
      com.google.protobuf.RpcController controller,
      com.example.fednclient.grpc.ControlRequest request,
      com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done);

  /**
   * <code>rpc Report(.grpc.ControlRequest) returns (.grpc.ReportResponse);</code>
   */
  public abstract void report(
      com.google.protobuf.RpcController controller,
      com.example.fednclient.grpc.ControlRequest request,
      com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.fednclient.grpc.Fedn.getDescriptor().getServices().get(1);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.start(controller, (com.example.fednclient.grpc.ControlRequest)request,
          com.google.protobuf.RpcUtil.<com.example.fednclient.grpc.ControlResponse>specializeCallback(
            done));
        return;
      case 1:
        this.stop(controller, (com.example.fednclient.grpc.ControlRequest)request,
          com.google.protobuf.RpcUtil.<com.example.fednclient.grpc.ControlResponse>specializeCallback(
            done));
        return;
      case 2:
        this.configure(controller, (com.example.fednclient.grpc.ControlRequest)request,
          com.google.protobuf.RpcUtil.<com.example.fednclient.grpc.ReportResponse>specializeCallback(
            done));
        return;
      case 3:
        this.report(controller, (com.example.fednclient.grpc.ControlRequest)request,
          com.google.protobuf.RpcUtil.<com.example.fednclient.grpc.ReportResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
      case 1:
        return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
      case 2:
        return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
      case 3:
        return com.example.fednclient.grpc.ControlRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.fednclient.grpc.ControlResponse.getDefaultInstance();
      case 1:
        return com.example.fednclient.grpc.ControlResponse.getDefaultInstance();
      case 2:
        return com.example.fednclient.grpc.ReportResponse.getDefaultInstance();
      case 3:
        return com.example.fednclient.grpc.ReportResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.fednclient.grpc.Control implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void start(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.fednclient.grpc.ControlResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.fednclient.grpc.ControlResponse.class,
          com.example.fednclient.grpc.ControlResponse.getDefaultInstance()));
    }

    public  void stop(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ControlResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.fednclient.grpc.ControlResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.fednclient.grpc.ControlResponse.class,
          com.example.fednclient.grpc.ControlResponse.getDefaultInstance()));
    }

    public  void configure(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.fednclient.grpc.ReportResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.fednclient.grpc.ReportResponse.class,
          com.example.fednclient.grpc.ReportResponse.getDefaultInstance()));
    }

    public  void report(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ReportResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.example.fednclient.grpc.ReportResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.fednclient.grpc.ReportResponse.class,
          com.example.fednclient.grpc.ReportResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.fednclient.grpc.ControlResponse start(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.fednclient.grpc.ControlResponse stop(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.fednclient.grpc.ReportResponse configure(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.fednclient.grpc.ReportResponse report(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.fednclient.grpc.ControlResponse start(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.fednclient.grpc.ControlResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.fednclient.grpc.ControlResponse.getDefaultInstance());
    }


    public com.example.fednclient.grpc.ControlResponse stop(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.fednclient.grpc.ControlResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.fednclient.grpc.ControlResponse.getDefaultInstance());
    }


    public com.example.fednclient.grpc.ReportResponse configure(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.fednclient.grpc.ReportResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.example.fednclient.grpc.ReportResponse.getDefaultInstance());
    }


    public com.example.fednclient.grpc.ReportResponse report(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ControlRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.fednclient.grpc.ReportResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.example.fednclient.grpc.ReportResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:grpc.Control)
}

