// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fednclient.grpc;

/**
 * Protobuf service {@code grpc.ModelService}
 */
public  abstract class ModelService
    implements com.google.protobuf.Service {
  protected ModelService() {}

  public interface Interface {
    /**
     * <code>rpc Upload(stream .grpc.ModelRequest) returns (.grpc.ModelResponse);</code>
     */
    public abstract void upload(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done);

    /**
     * <code>rpc Download(.grpc.ModelRequest) returns (stream .grpc.ModelResponse);</code>
     */
    public abstract void download(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new ModelService() {
      @java.lang.Override
      public  void upload(
          com.google.protobuf.RpcController controller,
          com.example.fednclient.grpc.ModelRequest request,
          com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done) {
        impl.upload(controller, request, done);
      }

      @java.lang.Override
      public  void download(
          com.google.protobuf.RpcController controller,
          com.example.fednclient.grpc.ModelRequest request,
          com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done) {
        impl.download(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.upload(controller, (com.example.fednclient.grpc.ModelRequest)request);
          case 1:
            return impl.download(controller, (com.example.fednclient.grpc.ModelRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.fednclient.grpc.ModelRequest.getDefaultInstance();
          case 1:
            return com.example.fednclient.grpc.ModelRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.fednclient.grpc.ModelResponse.getDefaultInstance();
          case 1:
            return com.example.fednclient.grpc.ModelResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Upload(stream .grpc.ModelRequest) returns (.grpc.ModelResponse);</code>
   */
  public abstract void upload(
      com.google.protobuf.RpcController controller,
      com.example.fednclient.grpc.ModelRequest request,
      com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done);

  /**
   * <code>rpc Download(.grpc.ModelRequest) returns (stream .grpc.ModelResponse);</code>
   */
  public abstract void download(
      com.google.protobuf.RpcController controller,
      com.example.fednclient.grpc.ModelRequest request,
      com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.fednclient.grpc.Fedn.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.upload(controller, (com.example.fednclient.grpc.ModelRequest)request,
          com.google.protobuf.RpcUtil.<com.example.fednclient.grpc.ModelResponse>specializeCallback(
            done));
        return;
      case 1:
        this.download(controller, (com.example.fednclient.grpc.ModelRequest)request,
          com.google.protobuf.RpcUtil.<com.example.fednclient.grpc.ModelResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.fednclient.grpc.ModelRequest.getDefaultInstance();
      case 1:
        return com.example.fednclient.grpc.ModelRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.fednclient.grpc.ModelResponse.getDefaultInstance();
      case 1:
        return com.example.fednclient.grpc.ModelResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.fednclient.grpc.ModelService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void upload(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.fednclient.grpc.ModelResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.fednclient.grpc.ModelResponse.class,
          com.example.fednclient.grpc.ModelResponse.getDefaultInstance()));
    }

    public  void download(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request,
        com.google.protobuf.RpcCallback<com.example.fednclient.grpc.ModelResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.fednclient.grpc.ModelResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.fednclient.grpc.ModelResponse.class,
          com.example.fednclient.grpc.ModelResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.fednclient.grpc.ModelResponse upload(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request)
        throws com.google.protobuf.ServiceException;

    public com.example.fednclient.grpc.ModelResponse download(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.fednclient.grpc.ModelResponse upload(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.fednclient.grpc.ModelResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.fednclient.grpc.ModelResponse.getDefaultInstance());
    }


    public com.example.fednclient.grpc.ModelResponse download(
        com.google.protobuf.RpcController controller,
        com.example.fednclient.grpc.ModelRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.fednclient.grpc.ModelResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.example.fednclient.grpc.ModelResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:grpc.ModelService)
}

