// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fedn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.fednclient.grpc;

@kotlin.jvm.JvmName("-initializemodelResponse")
public inline fun modelResponse(block: com.example.fednclient.grpc.ModelResponseKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.ModelResponse =
  com.example.fednclient.grpc.ModelResponseKt.Dsl._create(com.example.fednclient.grpc.ModelResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.ModelResponse`
 */
public object ModelResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.fednclient.grpc.ModelResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.fednclient.grpc.ModelResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.fednclient.grpc.ModelResponse = _builder.build()

    /**
     * `bytes data = 1;`
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * `bytes data = 1;`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `string id = 2;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.grpc.ModelStatus status = 3;`
     */
    public var status: com.example.fednclient.grpc.ModelStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.grpc.ModelStatus status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string message = 4;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * `string message = 4;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.fednclient.grpc.ModelResponse.copy(block: com.example.fednclient.grpc.ModelResponseKt.Dsl.() -> kotlin.Unit): com.example.fednclient.grpc.ModelResponse =
  com.example.fednclient.grpc.ModelResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

