// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fednclient.grpc;

public interface ModelValidationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ModelValidationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Client sender = 1;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.grpc.Client sender = 1;</code>
   * @return The sender.
   */
  com.example.fednclient.grpc.Client getSender();
  /**
   * <code>.grpc.Client sender = 1;</code>
   */
  com.example.fednclient.grpc.ClientOrBuilder getSenderOrBuilder();

  /**
   * <code>.grpc.Client receiver = 2;</code>
   * @return Whether the receiver field is set.
   */
  boolean hasReceiver();
  /**
   * <code>.grpc.Client receiver = 2;</code>
   * @return The receiver.
   */
  com.example.fednclient.grpc.Client getReceiver();
  /**
   * <code>.grpc.Client receiver = 2;</code>
   */
  com.example.fednclient.grpc.ClientOrBuilder getReceiverOrBuilder();

  /**
   * <code>string model_id = 3;</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <code>string model_id = 3;</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string correlation_id = 5;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlation_id = 5;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>string timestamp = 6;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 6;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string meta = 7;</code>
   * @return The meta.
   */
  java.lang.String getMeta();
  /**
   * <code>string meta = 7;</code>
   * @return The bytes for meta.
   */
  com.google.protobuf.ByteString
      getMetaBytes();

  /**
   * <code>bool is_inference = 8;</code>
   * @return The isInference.
   */
  boolean getIsInference();
}
