// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.fedn_client.grpc.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.fedn_client.grpc.Role role = 1;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.com.example.fedn_client.grpc.Role role = 1;</code>
   * @return The role.
   */
  com.example.fedn_client.grpc.Role getRole();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
