// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

/**
 * Protobuf enum {@code grpc.Command}
 */
public enum Command
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>IDLE = 0;</code>
   */
  IDLE(0),
  /**
   * <code>START = 1;</code>
   */
  START(1),
  /**
   * <code>PAUSE = 2;</code>
   */
  PAUSE(2),
  /**
   * <code>STOP = 3;</code>
   */
  STOP(3),
  /**
   * <code>RESET = 4;</code>
   */
  RESET(4),
  /**
   * <code>REPORT = 5;</code>
   */
  REPORT(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>IDLE = 0;</code>
   */
  public static final int IDLE_VALUE = 0;
  /**
   * <code>START = 1;</code>
   */
  public static final int START_VALUE = 1;
  /**
   * <code>PAUSE = 2;</code>
   */
  public static final int PAUSE_VALUE = 2;
  /**
   * <code>STOP = 3;</code>
   */
  public static final int STOP_VALUE = 3;
  /**
   * <code>RESET = 4;</code>
   */
  public static final int RESET_VALUE = 4;
  /**
   * <code>REPORT = 5;</code>
   */
  public static final int REPORT_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Command valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Command forNumber(int value) {
    switch (value) {
      case 0: return IDLE;
      case 1: return START;
      case 2: return PAUSE;
      case 3: return STOP;
      case 4: return RESET;
      case 5: return REPORT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Command>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Command> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Command>() {
          public Command findValueByNumber(int number) {
            return Command.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.fedn_client.grpc.Fedn.getDescriptor().getEnumTypes().get(4);
  }

  private static final Command[] VALUES = values();

  public static Command valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Command(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc.Command)
}

