// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

public interface ConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ConnectionRequest)
    com.google.protobuf.MessageOrBuilder {
}
