// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

/**
 * Protobuf enum {@code grpc.ConnectionStatus}
 */
public enum ConnectionStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NOT_ACCEPTING = 0;</code>
   */
  NOT_ACCEPTING(0),
  /**
   * <code>ACCEPTING = 1;</code>
   */
  ACCEPTING(1),
  /**
   * <code>TRY_AGAIN_LATER = 2;</code>
   */
  TRY_AGAIN_LATER(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NOT_ACCEPTING = 0;</code>
   */
  public static final int NOT_ACCEPTING_VALUE = 0;
  /**
   * <code>ACCEPTING = 1;</code>
   */
  public static final int ACCEPTING_VALUE = 1;
  /**
   * <code>TRY_AGAIN_LATER = 2;</code>
   */
  public static final int TRY_AGAIN_LATER_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConnectionStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ConnectionStatus forNumber(int value) {
    switch (value) {
      case 0: return NOT_ACCEPTING;
      case 1: return ACCEPTING;
      case 2: return TRY_AGAIN_LATER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConnectionStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConnectionStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConnectionStatus>() {
          public ConnectionStatus findValueByNumber(int number) {
            return ConnectionStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.fedn_client.grpc.Fedn.getDescriptor().getEnumTypes().get(5);
  }

  private static final ConnectionStatus[] VALUES = values();

  public static ConnectionStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConnectionStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc.ConnectionStatus)
}

