// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.fedn_client.grpc.Heartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   * @return The sender.
   */
  com.example.fedn_client.grpc.Client getSender();
  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   */
  com.example.fedn_client.grpc.ClientOrBuilder getSenderOrBuilder();
}
