// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fedn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.fedn_client.grpc;

@kotlin.jvm.JvmName("-initializelistClientsRequest")
public inline fun listClientsRequest(block: com.example.fedn_client.grpc.ListClientsRequestKt.Dsl.() -> kotlin.Unit): com.example.fedn_client.grpc.ListClientsRequest =
  com.example.fedn_client.grpc.ListClientsRequestKt.Dsl._create(com.example.fedn_client.grpc.ListClientsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.fedn_client.grpc.ListClientsRequest`
 */
public object ListClientsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.fedn_client.grpc.ListClientsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.fedn_client.grpc.ListClientsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.fedn_client.grpc.ListClientsRequest = _builder.build()

    /**
     * `.com.example.fedn_client.grpc.Client sender = 1;`
     */
    public var sender: com.example.fedn_client.grpc.Client
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * `.com.example.fedn_client.grpc.Client sender = 1;`
     */
    public fun clearSender() {
      _builder.clearSender()
    }
    /**
     * `.com.example.fedn_client.grpc.Client sender = 1;`
     * @return Whether the sender field is set.
     */
    public fun hasSender(): kotlin.Boolean {
      return _builder.hasSender()
    }

    /**
     * `.com.example.fedn_client.grpc.Queue channel = 2;`
     */
    public var channel: com.example.fedn_client.grpc.Queue
      @JvmName("getChannel")
      get() = _builder.getChannel()
      @JvmName("setChannel")
      set(value) {
        _builder.setChannel(value)
      }
    public var channelValue: kotlin.Int
      @JvmName("getChannelValue")
      get() = _builder.getChannelValue()
      @JvmName("setChannelValue")
      set(value) {
        _builder.setChannelValue(value)
      }
    /**
     * `.com.example.fedn_client.grpc.Queue channel = 2;`
     */
    public fun clearChannel() {
      _builder.clearChannel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.fedn_client.grpc.ListClientsRequest.copy(block: com.example.fedn_client.grpc.ListClientsRequestKt.Dsl.() -> kotlin.Unit): com.example.fedn_client.grpc.ListClientsRequest =
  com.example.fedn_client.grpc.ListClientsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.fedn_client.grpc.ListClientsRequestOrBuilder.senderOrNull: com.example.fedn_client.grpc.Client?
  get() = if (hasSender()) getSender() else null

