// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

public interface ModelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.fedn_client.grpc.ModelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   * @return The sender.
   */
  com.example.fedn_client.grpc.Client getSender();
  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   */
  com.example.fedn_client.grpc.ClientOrBuilder getSenderOrBuilder();

  /**
   * <code>.com.example.fedn_client.grpc.Client receiver = 2;</code>
   * @return Whether the receiver field is set.
   */
  boolean hasReceiver();
  /**
   * <code>.com.example.fedn_client.grpc.Client receiver = 2;</code>
   * @return The receiver.
   */
  com.example.fedn_client.grpc.Client getReceiver();
  /**
   * <code>.com.example.fedn_client.grpc.Client receiver = 2;</code>
   */
  com.example.fedn_client.grpc.ClientOrBuilder getReceiverOrBuilder();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string id = 4;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.com.example.fedn_client.grpc.ModelStatus status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.example.fedn_client.grpc.ModelStatus status = 5;</code>
   * @return The status.
   */
  com.example.fedn_client.grpc.ModelStatus getStatus();
}
