// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fedn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.fedn_client.grpc;

@kotlin.jvm.JvmName("-initializemodelRequest")
public inline fun modelRequest(block: com.example.fedn_client.grpc.ModelRequestKt.Dsl.() -> kotlin.Unit): com.example.fedn_client.grpc.ModelRequest =
  com.example.fedn_client.grpc.ModelRequestKt.Dsl._create(com.example.fedn_client.grpc.ModelRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `grpc.ModelRequest`
 */
public object ModelRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.fedn_client.grpc.ModelRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.fedn_client.grpc.ModelRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.fedn_client.grpc.ModelRequest = _builder.build()

    /**
     * `.grpc.Client sender = 1;`
     */
    public var sender: com.example.fedn_client.grpc.Client
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * `.grpc.Client sender = 1;`
     */
    public fun clearSender() {
      _builder.clearSender()
    }
    /**
     * `.grpc.Client sender = 1;`
     * @return Whether the sender field is set.
     */
    public fun hasSender(): kotlin.Boolean {
      return _builder.hasSender()
    }

    /**
     * `.grpc.Client receiver = 2;`
     */
    public var receiver: com.example.fedn_client.grpc.Client
      @JvmName("getReceiver")
      get() = _builder.getReceiver()
      @JvmName("setReceiver")
      set(value) {
        _builder.setReceiver(value)
      }
    /**
     * `.grpc.Client receiver = 2;`
     */
    public fun clearReceiver() {
      _builder.clearReceiver()
    }
    /**
     * `.grpc.Client receiver = 2;`
     * @return Whether the receiver field is set.
     */
    public fun hasReceiver(): kotlin.Boolean {
      return _builder.hasReceiver()
    }

    /**
     * `bytes data = 3;`
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * `bytes data = 3;`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `string id = 4;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 4;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.grpc.ModelStatus status = 5;`
     */
    public var status: com.example.fedn_client.grpc.ModelStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.grpc.ModelStatus status = 5;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.fedn_client.grpc.ModelRequest.copy(block: com.example.fedn_client.grpc.ModelRequestKt.Dsl.() -> kotlin.Unit): com.example.fedn_client.grpc.ModelRequest =
  com.example.fedn_client.grpc.ModelRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.fedn_client.grpc.ModelRequestOrBuilder.senderOrNull: com.example.fedn_client.grpc.Client?
  get() = if (hasSender()) getSender() else null

public val com.example.fedn_client.grpc.ModelRequestOrBuilder.receiverOrNull: com.example.fedn_client.grpc.Client?
  get() = if (hasReceiver()) getReceiver() else null

