// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fedn.proto

package com.example.fedn_client.grpc;

public interface TaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.fedn_client.grpc.TaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   * @return Whether the sender field is set.
   */
  boolean hasSender();
  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   * @return The sender.
   */
  com.example.fedn_client.grpc.Client getSender();
  /**
   * <code>.com.example.fedn_client.grpc.Client sender = 1;</code>
   */
  com.example.fedn_client.grpc.ClientOrBuilder getSenderOrBuilder();

  /**
   * <code>.com.example.fedn_client.grpc.Client receiver = 2;</code>
   * @return Whether the receiver field is set.
   */
  boolean hasReceiver();
  /**
   * <code>.com.example.fedn_client.grpc.Client receiver = 2;</code>
   * @return The receiver.
   */
  com.example.fedn_client.grpc.Client getReceiver();
  /**
   * <code>.com.example.fedn_client.grpc.Client receiver = 2;</code>
   */
  com.example.fedn_client.grpc.ClientOrBuilder getReceiverOrBuilder();

  /**
   * <code>string model_id = 3;</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <code>string model_id = 3;</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();

  /**
   * <pre>
   * data is round_config when type is MODEL_UPDATE
   * </pre>
   *
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <pre>
   * data is round_config when type is MODEL_UPDATE
   * </pre>
   *
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string correlation_id = 5;</code>
   * @return The correlationId.
   */
  java.lang.String getCorrelationId();
  /**
   * <code>string correlation_id = 5;</code>
   * @return The bytes for correlationId.
   */
  com.google.protobuf.ByteString
      getCorrelationIdBytes();

  /**
   * <code>string timestamp = 6;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 6;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string meta = 7;</code>
   * @return The meta.
   */
  java.lang.String getMeta();
  /**
   * <code>string meta = 7;</code>
   * @return The bytes for meta.
   */
  com.google.protobuf.ByteString
      getMetaBytes();

  /**
   * <code>string session_id = 8;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 8;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>.com.example.fedn_client.grpc.StatusType type = 9;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.example.fedn_client.grpc.StatusType type = 9;</code>
   * @return The type.
   */
  com.example.fedn_client.grpc.StatusType getType();
}
